# Site
repository: young891221/young891221.github.io
# favicon: images/favicon.ico

# Personal info
name: 김영재(작성중)
title: Java 백엔드 엔지니어
email: young891221@gmail.com
website: https://haviyj.tistory.com

# Social links
# twitter_username: young891221
github_username:  young891221
# dribbble_username: jekyll
#facebook_username: young891221
# flickr_username: jekyll
# linkedin_username: jojoldu
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  7년차 백엔드 개발자로 LINE의 분산 처리 환경에서 **월 평균 14억건**의 결제 시스템과 **일 PV 2,000만** 환경의 ZUM포털에서 다양한 개발 경험을 쌓았습니다.
  팀 내 생산성을 높이고 동료들에게 선한 영향력을 행사하고자 노력하였습니다. 덕분에 legacy 시스템을 개선시켜 다양한 자동화 모듈들을 개발하였고 효과적인 모니터링 운영 방식을 도입시켜 인정받았습니다.
  신규 결제 시스템을 개발하면서 다방면의 성능 튜닝 업무를 진행하였고 관련된 오픈소스들의 성능을 분석하여 문제점을 개선시키거나 더 나은 방향성을 제시하고 해결한 경험이 있습니다.
  최근에는 **9천만 유저, 약 1000억건**의 결제 내역을 실시간 마이그레이션 처리하는 업무를 진행하였습니다.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   [처음 시작하는 Spring Boot2(한빛미디어) 출간](http://www.yes24.com/Product/Goods/64584833?OzSrank=6)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
